CC = gcc
CFLAGS = -I /usr/local/include  -DUNIX
COUT = -o 
LN = gcc
LDFLAGS =  
LIBS =-L /usr/local/lib -lodbc
LNOUT = -o 
EXESUFFICS =
OBJSUFFICS = .o
DEFINEOPTION = -D
COMPFILES = *~
REMOVECOMMAND = rm -f
COMPATLIBS =

include Makefile.inc
