.TH tcppm "8" "January 2019" "3proxy 0.9" "Universal proxy server"
.SH NAME
.B tcppm
\- TCP port mapper
.SH SYNOPSIS
.BR "tcppm " [ -d ]
.IB \fR[ -l \fR[ \fR[ @ \fR] logfile \fR]]
.IB \fR[ -i internal_ip\fR]
.IB \fR[ -e external_ip\fR]
.I local_port remote_host remote_port
.SH DESCRIPTION
.B tcppm
forwards connections from local to remote TCP port
.SH OPTIONS
.TP
.B -I
Inetd mode. Standalone service only.
.TP
.B -d
Daemonize. Detach service from console and run in the background.
.TP
.B -t
Be silenT. Do not log start/stop/accept error records.
.TP
.B -e
External address. IP address of the interface the proxy should initiate connections
from.
By default, the system will decide which address to use in accordance
with the routing table.
.TP
.B -i
Internal address. IP address the proxy accepts connections to.
By default, connections to any interface are accepted. It\'s usually unsafe.
Unix domain sockets can be specified with
.I -iunix:/path/to/socket
syntax (e.g., -iunix:/var/run/tcppm.sock). On Linux, abstract sockets use
.I -iunix:@socketname
syntax.
.TP
.B -l
Log. By default logging is to stdout. If
.I logfile
is specified logging is to file. Under Unix, if
.RI \' @ \'
precedes
.IR logfile ,
syslog is used for logging.
.TP
.B -S
Increase or decrease stack size. You may want to try something like -S8192 if you experience 3proxy
crashes.
.SH ARGUMENTS
.TP
.I local_port
- port tcppm accepts connections on
.TP
.I remote_host
- IP address of the host the connection is forwarded to. Unix domain sockets
can be specified with the syntax
.I unix:/path/to/socket
(e.g., unix:/var/run/app.sock). On Linux, abstract (fileless) Unix sockets
use the syntax
.I unix:@socketname
(e.g., unix:@app.socket).
.TP
.I remote_port
- remote port the connection is forwarded to. Ignored when using Unix socket
destination, but must be specified (use any positive value) for syntax
compatibility.
.SH CLIENTS
Any TCP-based application can be used as a client. Use
.I internal_ip
and
.I local_port
as the destination in the client application. The connection is forwarded to
.IR remote_host : remote_port
.SH BUGS
Report all bugs to
.BR 3proxy@3proxy.org
.SH SEE ALSO
3proxy(8), proxy(8), ftppr(8), socks(8), pop3p(8), udppm(8), syslogd(8),
.br
https://3proxy.org/
.SH AUTHORS
3proxy is designed by Vladimir 3APA3A Dubrovin
.RI ( 3proxy@3proxy.org )
