name: C/C++ CI

on:
  push:
    branches: [ "test-ci" ]
    paths: [ 'RELEASE', '.github/workflows/build-win32.yml' ]

jobs:
  ci:
    name: "${{ matrix.target }}"
    strategy:
      matrix:
        target:
          - windows-2022
    runs-on: ${{ matrix.target }}
    steps:
    - uses: actions/checkout@v4
#    - name: configure
#      run: ./configure
    - name: set date
      run: |
       $NOW = Get-Date -Format "yyMMddHHmmss"
       echo "now: $NOW"
       $RELEASE = Get-Content -Path "RELEASE" -Raw
       echo "release: $RELEASE"
       echo "NOW=$NOW" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       echo "RELEASE=$RELEASE" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       echo "VERSION=VERSION=`"$RELEASE`"" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       echo "BUILDDATE=BUILDDATE=`"$NOW`"" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
       echo "COMMONFILES=cfg/*.* cfg/sql/*.* doc/ru/*.* doc/html/*.* doc/html/plugins/*.* doc/html/man8/*.* doc/html/man3/*.* doc/devel/*.rtf copying authors README rus.3ps" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
    - name: install packages
      run: vcpkg install pcre2:x86-windows openssl:x86-windows
    - name: echo variables
      shell: cmd
      run: |
       echo builddate:%BUILDDATE% release:%RELEASE% version:%VERSION% now:%NOW%
       dir "c:\program files\openssl\lib\VC"
       dir "c:\vcpkg\installed"
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v3
    - name: make Windows MSVC
      if: ${{ startsWith(matrix.target, 'windows') }}
      shell: cmd
      run: |
       call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
       D:
       cd "D:/a/3proxy/3proxy"
       set "LIB=%LIB%;c:/vcpkg/installed/x86-windows/lib"
       set "INCLUDE=%INCLUDE%;c:/vcpkg/installed/x86-windows/include"
       nmake /F Makefile.msvc
       cp c:/vcpkg/installed/x86-windows/*.dll bin/
    - name: Get artifact
      uses: actions/upload-artifact@v4
      with:
       name: "3proxy-${{ env.RELEASE }}.zip"
       path: |
        bin/3proxy.exe
        bin/*.dll
        bin/mycrypt.exe
        cfg/*.*
        cfg/sql/*.*
        doc/ru/*.*
        doc/html/*.*
        doc/html/plugins/*.*
        doc/html/man8/*.*
        doc/html/man3/*.*
        doc/devel/*.rtf
        copying
        authors
        README
        rus.3ps
